# Generated by Django 5.1.4 on 2025-01-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(max_length=20),
        ),
    ]
