# Generated by Django 5.1.4 on 2025-01-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swc', '0004_alter_contact_email_alter_contact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
