# Generated by Django 5.1.1 on 2025-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_addcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
